.class interface abstract Lcom/synerise/sdk/synalter/model/SynalterMockResponse$SynalterMocks;
.super Ljava/lang/Object;
.source "SynalterMockResponse.java"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/synerise/sdk/synalter/model/SynalterMockResponse;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x60a
    name = "SynalterMocks"
.end annotation


# static fields
.field public static final mockSynalter:Ljava/lang/String; = "{\n  \"is_debug\": false,\n  \"synalter_data\": [\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.MainActivity\",\n      \"modified_data\": {\n        \"id\": \"menu_button_tracker\",\n        \"text\": \"Synaltered Text\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.synalter.app.SynalterActivity\",\n      \"modified_data\": {\n        \"id\": \"button_1\",\n        \"text\": \"Synaltered Text\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.events.widgets.recycler.adapter.CustomersRecyclerAdapter\",\n      \"modified_data\": {\n        \"id\": \"customer_lastname\",\n        \"text\": \"Synaltered Text\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.synalter.support.SynalterSupportActivity\",\n      \"modified_data\": {\n        \"id\": \"button_1\",\n        \"text\": \"Synaltered Text\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.synalter.support.TestSupportFragment\",\n      \"modified_data\": {\n        \"id\": \"fragment_button\",\n        \"text\": \"Synaltered Text\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    }\n  ]\n}"

.field public static final mockSynalterEmail:Ljava/lang/String; = "{\n  \"is_debug\": true,\n  \"synalter_data\": [\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.MainActivity\",\n      \"modified_data\": {\n        \"id\": \"menu_button_tracker\",\n        \"text\": \"Synaltered Text Debug\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.synalter.app.SynalterActivity\",\n      \"modified_data\": {\n        \"id\": \"button_1\",\n        \"text\": \"Synaltered Text Debug\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.events.widgets.recycler.adapter.CustomersRecyclerAdapter\",\n      \"modified_data\": {\n        \"id\": \"customer_lastname\",\n        \"text\": \"Synaltered Text Debug\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.synalter.support.SynalterSupportActivity\",\n      \"modified_data\": {\n        \"id\": \"button_1\",\n        \"text\": \"Synaltered Text Debug\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    },\n    {\n      \"date\": \"2018-01-01T10:10:10.100Z\",\n      \"origin\": \"some_test_origin\",\n      \"component_path\": \"com.synerise.sdk.sample.view.synalter.support.TestSupportFragment\",\n      \"modified_data\": {\n        \"id\": \"fragment_button\",\n        \"text\": \"Synaltered Text Debug\"\n      },\n      \"valid_through\": {\n        \"valid_from\": \"2018-01-01T10:10:10.100Z\",\n        \"valid_to\": \"2018-10-10T10:10:10.100Z\"\n      }\n    }\n  ]\n}"
